### ISSUE TITLE
Cleanup strings classes

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/Dragon6-API#138]
Was thinking on a couple of changes:

- [x] Change the static vars to getters (See #148)
- [x] Remove `:infinite` from the ends of each one and then use them in the requests (See #147)
- [x] Add an internal extension for a string to add the `:internal` part back on (See #147)
